apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: final-16
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector:
    app: prometheus-server
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: 9090